---
- name: Converge
  hosts: all
  # コンテナ内操作は通常root権限が必要なので有効化します
  become: true
  
  # 必要に応じてFacts収集を無効化できますが、通常はtrue（デフォルト）です
  gather_facts: true

  tasks:
    - name: "Include core role"
      include_role:
        name: "os_baseline.rhel_baseline.core"
