---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  # no_log: "{{ molecule_no_log }}"
  collections:
    - community.docker

  vars:
    container_name: instance

  tasks:
    - name: Destroy Docker container
      # create.ymlで作成したコンテナの削除
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent
        force_kill: true
