---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: instance
    image: geerlingguy/docker-rockylinux9-ansible:latest
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: "/usr/sbin/init"
    # pre_build_image は通常 false で良いですが、特定用途で true にする場合もあります
    pre_build_image: true

provisioner:
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: "1"
  ansible_args:
    - --diff

verifier:
  name: testinfra
  